[package]
name = "trade_networks"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json="^1.0.107"
serde={version="^1.0.189", features = ["derive"] }
clap = {version = "^4.4.8", features=["derive", "cargo", "color", "help"]}
bincode = "1.3.3"
rayon = "^1.8.0"
net_ensembles = { git = "https://github.com/Pardoxa/net_ensembles.git", rev = "f7922afeb09a7c9c8c48cf01326355780bfd7193" }
indicatif="^0.17.7"
anyhow = "^1.0.75"
strum = { version = "0.25", features = ["derive"] }
lazy_static = "^1.4.0"
sampling = { git = "https://github.com/Pardoxa/sampling.git", rev = "1f271e3ff97e52efcaeac9e807e6dffa05722cd9" }
itertools = "0.12.0"
glob = "0.3.1"
[profile.release]
# lto = true
# strip = true